Repository calliope-project/euro-calliope, pull requests merged in 2021-07, with the labels that each got.

#99 Update EEZ data source to enable direct download in the workflow
  CHANGELOG.md
  README.md
  config/default.yaml
  rules/shapes.smk
  scripts/capacityfactors_offshore.py
Labels: data

#112 split data folder into separate repo
  README.md
  Snakefile
  config/default.yaml
  config/schema.yaml
  data/biofuels/README.md
  data/biofuels/costs/README.md
  data/biofuels/costs/forestry-energy-residues.csv
  data/biofuels/costs/landscape-care-residues.csv
  data/biofuels/costs/manure.csv
  data/biofuels/costs/municipal-waste.csv
  data/biofuels/costs/primary-agricultural-residues.csv
  data/biofuels/costs/roundwood-chips.csv
  data/biofuels/costs/roundwood-fuelwood.csv
  data/biofuels/costs/secondary-forestry-residues-sawdust.csv
  data/biofuels/costs/secondary-forestry-residues-woodchips.csv
  data/biofuels/costs/sludge.csv
  data/biofuels/potentials/README.md
  data/biofuels/potentials/forestry-energy-residues.csv
  data/biofuels/potentials/landscape-care-residues.csv
  data/biofuels/potentials/manure.csv
  data/biofuels/potentials/municipal-waste.csv
  data/biofuels/potentials/primary-agricultural-residues.csv
  data/biofuels/potentials/roundwood-chips.csv
  data/biofuels/potentials/roundwood-fuelwood.csv
  data/biofuels/potentials/secondary-forestry-residues-sawdust.csv
  data/biofuels/potentials/secondary-forestry-residues-woodchips.csv
  data/biofuels/potentials/sludge.csv
  data/continental/land-cover.csv
  data/continental/technical-potential/farmland.csv
  data/irena/README.md
  data/irena/hydro-generation-europe.csv
  data/national/land-cover.csv
  data/national/technical-potential/farmland.csv
  data/pumped-hydro/README.md
  data/pumped-hydro/storage-capacities-gwh.csv
  data/regional/land-cover.csv
  data/regional/technical-potential/farmland.csv
  notebooks/preprocess-irena-data.ipynb
Labels: data

#141 Fix download of EEZ to happen on local (login) node
  rules/shapes.smk
Labels: bug

#140 Fix syncignore to ignore data/euro-calliope-datasets
  .syncignore-send
Labels: bug

#142 Update Snakemake to use mamba by default
  CHANGELOG.md
  README.md
  Snakefile
  environment.yaml
Labels: enhancement

#147 Fix determination of location centroids
  CHANGELOG.md
  scripts/locations.py
  tests/model/test_model.py
Labels: bug

#153 Add config option to choose solar and wind potential scenario
  CHANGELOG.md
  Snakefile
  config/default.yaml
  config/schema.yaml
Labels: documentation, enhancement
