Repository calliope-project/euro-calliope, pull requests merged in 2021-04, with the labels that each got.

#44 Update atlite and geo packages
  CHANGELOG.md
  environment.yaml
  envs/default.yaml
  envs/geo.yaml
  envs/hydro.yaml
  envs/test.yaml
  rules/hydro.smk
  src/hydro/inflow_m3.py
  src/hydro/runoff.py
Labels: hydro

#45 Update handling of folders and urls
  .gitignore
  CHANGELOG.md
  README.md
  Snakefile
  config/default.yaml
  config/schema.yaml
  rules/hydro.smk
  rules/shapes.smk
  scripts/biofuels.py
  scripts/capacityfactors.py
  scripts/capacityfactors_hydro.py
  scripts/capacityfactors_offshore.py
  scripts/directional_rooftop.py
  scripts/filters.py
  scripts/hydro.py
  scripts/hydro/fix_basins.py
  scripts/hydro/inflow_m3.py
  scripts/hydro/inflow_mwh.py
  scripts/hydro/preprocess_hydro_stations.py
  scripts/hydro/runoff.py
  scripts/link_neighbours.py
  scripts/load.py
  scripts/load_shedding.py
  scripts/locations.py
  scripts/metadata.py
  scripts/national_load.py
  scripts/parameterise_templates.py
  scripts/shapes/gadm.py
  scripts/shapes/nogeo.py
  scripts/shapes/nuts.py
  scripts/shapes/units.py
  templates/README.md
  templates/demand-techs.yaml
  templates/environment.yaml
  templates/example-model.yaml
  templates/interest-rate.yaml
  templates/link-techs.yaml
  templates/renewable-techs.yaml
  templates/storage-techs.yaml
Labels: enhancement

#48 update-jrc-hydro-from-develop
  CHANGELOG.md
  config/default.yaml
  rules/hydro.smk
  scripts/hydro/preprocess_hydro_stations.py
Labels: data, hydro

#53 Update to remove conflicts associated with py3.8
  envs/default.yaml
Labels: bug

#49 Make scaling PHS with Geth et al. optional
  CHANGELOG.md
  Snakefile
  config/default.yaml
  config/schema.yaml
  scripts/hydro.py
Labels: data, hydro

#40 Update IRENA hydro generation data
  CHANGELOG.md
  README.md
  data/irena/README.md
  data/irena/hydro-generation-europe.csv
  notebooks/preprocess-irena-data.ipynb
  scripts/hydro/inflow_mwh.py
Labels: data, hydro

#46 Update citation
  CITATION.md
  README.md
Labels: documentation

#51 Add automatic download of hydro basins database
  CHANGELOG.md
  README.md
  config/default.yaml
  config/schema.yaml
  rules/hydro.smk
Labels: data, hydro

#58 Fix issues with JRC hydro stations database v07
  .github/workflows/pythonpackage.yaml
  README.md
  envs/default.yaml
  envs/geo.yaml
  envs/hydro.yaml
  lib/README.md
  lib/eurocalliopelib/__init__.py
  lib/eurocalliopelib/utils.py
  lib/pytest.ini
  lib/requirements-test.txt
  lib/setup.py
  lib/tests/test_utils.py
  scripts/biofuels.py
  scripts/hydro/preprocess_hydro_stations.py
  scripts/metadata.py
  scripts/shapes/nuts.py
Labels: bug

#42 Entsoe data priority
  CHANGELOG.md
  Snakefile
  config/default.yaml
  config/schema.yaml
  scripts/national_load.py
Labels: data

#3 Add gap filling of national electricity demand from other years
  CHANGELOG.md
  Snakefile
  config/default.yaml
  config/minimal.yaml
  config/schema.yaml
  rules/hydro.smk
  scripts/national_load.py
Labels: data

#75 Add cluster sync infrastructure
  .gitignore
  .syncignore-receive
  .syncignore-send
  CHANGELOG.md
  README.md
  Snakefile
  config/default.yaml
  config/schema.yaml
  envs/shell.yaml
  rules/sync.smk
Labels: enhancement

#72 Update contributions
  LICENSE.md
  README.md
Labels: documentation

#96 Update rules to make downloads consistent
  README.md
  Snakefile
  rules/shapes.smk
Labels: documentation

#92 Add optional email notifications
  CHANGELOG.md
  README.md
  Snakefile
  config/schema.yaml
Labels: enhancement
